"""
The real-photograph corpus builder.

The synthetic corpus is generated by us, which has always been the softest
part of the evidence. This builder lays real photographs out on a disk image
with real photographs as the surrounding junk, so the result is a claim about
photographs rather than about our own generator.

These tests use generated JPEGs written to disk as stand-ins, so the suite
still runs from a clean clone with no photo library present. What they cover
is the builder's machinery -- selection, layout, ground truth -- not the
quality of any particular photo set.
"""

from __future__ import annotations

import io
import json
import os

import pytest
from PIL import Image

from carve.blocks import SOI, ClusterView
from corpus.generate.real_photos import (RealPhotoFiller, build_easy, build_hard,
                                         find_photos, usable)
from corpus.generate.synthetic import CLUSTER, encode_jpeg, make_photo


@pytest.fixture(scope="module")
def photo_dir(tmp_path_factory):
    """A folder of baseline JPEGs big enough to fragment, plus two rejects."""
    d = tmp_path_factory.mktemp("photos")
    for i in range(8):
        # 900x700 at high quality lands comfortably above the 6-cluster floor
        data = encode_jpeg(make_photo(900, 700, seed=i + 1), quality=92)
        (d / ("photo_%02d.jpg" % i)).write_bytes(data)

    # a file too small to fragment
    (d / "tiny.jpg").write_bytes(encode_jpeg(make_photo(64, 64, seed=99), quality=30))

    # a progressive JPEG, which the decoder does not support
    buf = io.BytesIO()
    make_photo(900, 700, seed=50).save(buf, format="JPEG", quality=92, progressive=True)
    (d / "progressive.jpg").write_bytes(buf.getvalue())

    return d


# --------------------------------------------------------------------------
# selection
# --------------------------------------------------------------------------

def test_finds_every_jpeg(photo_dir):
    assert len(find_photos(str(photo_dir))) == 10


def test_accepts_a_baseline_photo(photo_dir):
    got = usable(str(photo_dir / "photo_00.jpg"))
    assert got is not None
    data, mcus = got
    assert mcus > 0
    assert len(data) >= 6 * CLUSTER


def test_rejects_a_progressive_jpeg(photo_dir):
    """
    Baseline only. Progressive scans are not implemented, and silently
    accepting them would produce a misleading pass rate.
    """
    assert usable(str(photo_dir / "progressive.jpg")) is None


def test_rejects_a_photo_too_small_to_fragment(photo_dir):
    assert usable(str(photo_dir / "tiny.jpg")) is None


def test_rejects_a_file_that_is_not_a_jpeg(tmp_path):
    f = tmp_path / "notes.jpg"
    f.write_bytes(b"this is not a jpeg" * 2000)
    assert usable(str(f)) is None


# --------------------------------------------------------------------------
# filler
# --------------------------------------------------------------------------

def _photos(photo_dir, n=6):
    return [usable(str(photo_dir / ("photo_%02d.jpg" % i)))[0] for i in range(n)]


def test_filler_needs_at_least_one_usable_decoy():
    with pytest.raises(SystemExit):
        RealPhotoFiller([b"tiny"], seed=1)


def test_filler_decoy_bodies_carry_no_header(photo_dir):
    """
    Decoys are stripped of their first 1024 bytes. A decoy that kept its SOI
    would be a real file to carve, not filler, and would corrupt ground truth.
    """
    f = RealPhotoFiller(_photos(photo_dir), seed=1)
    for body in f.decoy_bodies:
        assert not body.startswith(SOI)


def test_filler_produces_full_clusters(photo_dir):
    f = RealPhotoFiller(_photos(photo_dir), seed=1)
    for _ in range(50):
        assert len(f.cluster()) == CLUSTER


# --------------------------------------------------------------------------
# layout and ground truth
# --------------------------------------------------------------------------

@pytest.fixture(scope="module")
def built(photo_dir, tmp_path_factory):
    out = tmp_path_factory.mktemp("images")
    photos = [usable(str(photo_dir / ("photo_%02d.jpg" % i)))[0] for i in range(8)]
    evidence = [("photo_00.jpg", photos[0]), ("photo_01.jpg", photos[1]),
                ("photo_02.jpg", photos[2])]
    decoys = photos[3:]
    easy = build_easy(str(out), evidence, decoys, 2048, seed=1)
    hard = build_hard(str(out), evidence, decoys, 2048, seed=1)
    return easy, hard


def test_hard_layout_contains_a_backward_jump(built):
    """The whole point of the hard case: the header's successor sits earlier
    on the disk, which is outside a forward-only carver's search space."""
    _, (_, manifest) = built
    order = manifest["files"][0]["cluster_order"]
    assert any(b < a for a, b in zip(order, order[1:]))


def test_manifest_cluster_order_matches_the_fragments(built):
    for _, manifest in built:
        for f in manifest["files"]:
            rebuilt = []
            for fr in sorted(f["fragments"], key=lambda d: d["fragment"]):
                rebuilt.extend(range(fr["start_cluster"],
                                     fr["start_cluster"] + fr["n_clusters"]))
            assert f["cluster_order"] == rebuilt


def test_manifest_records_a_real_source(built):
    for _, manifest in built:
        assert manifest["source"] == "real photographs"


def test_easy_image_holds_two_files_and_hard_holds_one(built):
    (_, easy), (_, hard) = built
    assert len(easy["files"]) == 2
    assert len(hard["files"]) == 1


def test_only_the_evidence_files_look_like_headers(built):
    """
    Decoy filler must not produce spurious JPEG headers at cluster boundaries,
    or the carver would chase files that do not exist and ground truth would
    be wrong.
    """
    for path, manifest in built:
        found = ClusterView(path).find_jpeg_headers()
        expected = sorted(f["cluster_order"][0] for f in manifest["files"])
        assert sorted(found) == expected


# --------------------------------------------------------------------------
# Deliberately NOT tested here: whether the carver actually solves a layout
# this builder produces.
#
# It solves some and not others. On a real webcam corpus (1280x720, 3600 MCU,
# 8192-cluster image) it recovers 3/3 byte-exact; on a 900x700 layout in a
# 2048-cluster image it fails, reaching 2503 of 2508 MCUs through a wrong
# 11-fragment assembly instead of the true 3-fragment path. See CLAUDE.md
# section 5g.
#
# That is a research result, not a regression invariant. Asserting it would
# either make CI red on a known-hard case or push someone to tune the corpus
# until it passes, which is the one thing this project must not do. The
# builder's contract is that it produces correct layouts and correct ground
# truth; the tests above check exactly that.
# --------------------------------------------------------------------------
