"""
Build benchmark disk images from REAL photographs instead of synthetic ones.

Why this exists
---------------
The synthetic corpus is generated by us, which is the softest part of the
evidence: our discriminator is tuned on images our own encoder produced. This
builds the same two layouts out of photographs the tool has never seen, so the
result is a claim about photographs rather than about our generator.

It is deliberately harder than the synthetic corpus in three ways:

  1. **Decoy filler is other real photographs**, not a synthetic decoy. When
     every photo comes off the same camera at the same settings, competing
     fragments share the standard Huffman tables AND the photometric
     statistics, which is precisely the case section 5f measures as unsolved
     (rejection falls to 19-38% for files without restart markers).
  2. **Real photos are larger** -- 30-40 clusters against 17 for the synthetic
     ones -- so the search space is bigger.
  3. **Nothing is tuned to them.** No seed, no label, no chosen quality.

Baseline JPEG only. Progressive files are skipped with a message: the decoder
does not implement progressive scans, and pretending otherwise would produce a
misleading pass rate.

Usage
-----
    tessera-gen-real --src "C:/Users/me/Pictures" --out corpus/images

Ground truth goes to a manifest in the same format as synthetic.py, so
bench/score.py and the carver need no changes.
"""

from __future__ import annotations

import argparse
import glob
import hashlib
import json
import os
import random
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from carve.validators import jpeg as J
from corpus.generate.synthetic import CLUSTER, DiskBuilder, Filler, split_at_clusters


def find_photos(src: str) -> list:
    """Every JPEG under `src`, recursively."""
    out = []
    for ext in ("jpg", "jpeg", "JPG", "JPEG"):
        out.extend(glob.glob(os.path.join(src, "**", "*." + ext), recursive=True))
    return sorted(set(out))


def usable(path: str, min_clusters: int = 6):
    """
    Load a photo if our decoder can actually handle it.

    Returns (data, total_mcus) or None. Rejects progressive JPEGs (unsupported)
    and anything too small to fragment meaningfully.
    """
    try:
        with open(path, "rb") as fh:
            data = fh.read()
        header = J.parse_header(data, 0)
    except Exception:
        return None
    if len(data) < min_clusters * CLUSTER:
        return None
    return data, header.total_mcus


class RealPhotoFiller(Filler):
    """
    Unallocated space whose decoy JPEG bodies are REAL photographs.

    Same zeros/text/random mix as the synthetic filler, but the decoy bodies
    come from headerless slices of other real photos rather than one small
    synthetic image. Those are the competitors the beam search must reject,
    and off the same camera they are as confusable as it gets.
    """

    def __init__(self, decoys: list, seed: int = 42):
        super().__init__(seed=seed)
        # strip each decoy's header so it cannot be mistaken for a file to carve
        self.decoy_bodies = [d[1024:] for d in decoys if len(d) > 2 * CLUSTER]
        if not self.decoy_bodies:
            raise SystemExit("need at least one decoy photo larger than 8 KB")

    def cluster(self) -> bytes:
        r = self.rnd.random()
        if r < 0.30:
            return b"\x00" * CLUSTER
        if r < 0.52:
            parts = []
            while sum(len(p) for p in parts) < CLUSTER:
                parts.append((" ".join(self.rnd.choice(self.words)
                                       for _ in range(self.rnd.randint(6, 14)))
                              + "\r\n").encode())
            return b"".join(parts)[:CLUSTER]
        if r < 0.90:
            body = self.rnd.choice(self.decoy_bodies)
            o = self.rnd.randrange(0, len(body) - CLUSTER)
            return body[o:o + CLUSTER]
        return bytes(self.rnd.getrandbits(8) for _ in range(CLUSTER))


def write_manifest(out_dir, img_path, kind, total_clusters, raw, placed, files):
    by_file = {}
    for name, idx, start, n in placed:
        by_file.setdefault(name, []).append(
            {"fragment": idx, "start_cluster": start, "n_clusters": n})

    manifest = {
        "image": os.path.basename(img_path),
        "kind": kind,
        "cluster_size": CLUSTER,
        "total_clusters": total_clusters,
        "size_bytes": len(raw),
        "source": "real photographs",
        "files": [],
    }
    for name, data in files.items():
        frags = sorted(by_file[name], key=lambda d: d["fragment"])
        order = []
        for fr in frags:
            order.extend(range(fr["start_cluster"], fr["start_cluster"] + fr["n_clusters"]))
        manifest["files"].append({
            "name": name,
            "size_bytes": len(data),
            "sha256": hashlib.sha256(data).hexdigest(),
            "n_fragments": len(frags),
            "fragments": frags,
            "cluster_order": order,
        })
        with open(os.path.join(out_dir, "truth_" + name), "wb") as fh:
            fh.write(data)

    with open(os.path.join(out_dir, "%s.manifest.json" % kind), "w") as fh:
        json.dump(manifest, fh, indent=2)
    return manifest


def build_easy(out_dir, evidence, decoys, total_clusters, seed):
    """Two real photos interleaved, each file's fragments in increasing order."""
    (na, a), (nb, bdata) = evidence[0], evidence[1]
    b = DiskBuilder(total_clusters, RealPhotoFiller(decoys, seed=seed + 500))

    a1, a2 = split_at_clusters(a, [0.45])
    b1, b2 = split_at_clusters(bdata, [0.45])
    b.place(na, 0, a1, at=120)
    b.place(nb, 0, b1, at=b.cursor + 2)
    b.place(na, 1, a2, at=b.cursor + 3)
    b.place(nb, 1, b2, at=b.cursor + 2)

    raw = b.finish()
    path = os.path.join(out_dir, "real_easy.img")
    with open(path, "wb") as fh:
        fh.write(raw)
    return path, write_manifest(out_dir, path, "real_easy", total_clusters, raw,
                                b.placed, {na: a, nb: bdata})


def build_hard(out_dir, evidence, decoys, total_clusters, seed):
    """One real photo in three fragments, out of order, with a backward jump."""
    name, data = evidence[2]
    b = DiskBuilder(total_clusters, RealPhotoFiller(decoys, seed=seed + 900))

    f1, f2, f3 = split_at_clusters(data, [0.34, 0.67])
    # fragment 2 lands BEFORE fragment 1, so the header's successor is backwards
    b.place(name, 1, f2, at=90)
    b.place(name, 0, f1, at=b.cursor + 14)
    b.place(name, 2, f3, at=b.cursor + 9)

    raw = b.finish()
    path = os.path.join(out_dir, "real_hard.img")
    with open(path, "wb") as fh:
        fh.write(raw)
    return path, write_manifest(out_dir, path, "real_hard", total_clusters, raw,
                                b.placed, {name: data})


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Build benchmark disk images from real photographs")
    ap.add_argument("--src", required=True, help="directory of real JPEGs (searched recursively)")
    ap.add_argument("--out", default=os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "images"))
    ap.add_argument("--size-mib", type=int, default=32)
    ap.add_argument("--seed", type=int, default=1)
    args = ap.parse_args()

    paths = find_photos(args.src)
    if not paths:
        print("no JPEGs found under %s" % args.src)
        return 1

    loaded, skipped = [], []
    for p in paths:
        got = usable(p)
        if got is None:
            skipped.append(p)
        else:
            loaded.append((os.path.basename(p), got[0], got[1]))

    print("found %d JPEG(s); %d usable, %d skipped (progressive or too small)"
          % (len(paths), len(loaded), len(skipped)))
    for p in skipped:
        print("   skipped: %s" % os.path.basename(p))
    if len(loaded) < 4:
        print("need at least 4 usable photos (3 evidence + 1 decoy)")
        return 1

    rnd = random.Random(args.seed)
    rnd.shuffle(loaded)
    evidence = [(n, d) for n, d, _ in loaded[:3]]
    decoys = [d for _, d, _ in loaded[3:]]

    os.makedirs(args.out, exist_ok=True)
    total_clusters = args.size_mib * 1024 * 1024 // CLUSTER

    print("\nevidence photos:")
    for n, d in evidence:
        print("   %-40s %8d B  %d clusters" % (n, len(d), -(-len(d) // CLUSTER)))
    print("decoy filler: %d other real photo(s)\n" % len(decoys))

    for builder in (build_easy, build_hard):
        path, manifest = builder(args.out, evidence, decoys, total_clusters, args.seed)
        print("%-16s -> %s  (%d MiB, %d clusters)"
              % (manifest["kind"], os.path.basename(path),
                 manifest["size_bytes"] // 1048576, manifest["total_clusters"]))
        for f in manifest["files"]:
            spans = ", ".join("c%d..%d" % (fr["start_cluster"],
                                           fr["start_cluster"] + fr["n_clusters"] - 1)
                              for fr in f["fragments"])
            print("   %-40s %7d B  %d frag  [%s]  sha=%s"
                  % (f["name"], f["size_bytes"], f["n_fragments"], spans,
                     f["sha256"][:16]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
